### ISSUE TITLE
[BUG] Could not load dataset 'Trace' with load_classification

### ISSUE THREAD

**Issue by simiaolin** [aeon-toolkit/aeon#1584]
### Describe the bug

I can only use `load_classification` to load a few datasets. For other datasets, e.g. Trace dataset, I could not load them correctly.

### Steps/Code to reproduce the bug

```from aeon.datasets import load_classification
from aeon.datasets.tsc_datasets import univariate
print(univariate)
X, y, meta_data = `load_classification`("Trace", return_metadata=True)
print(" Shape of X = ", X.shape)
print(" Meta data = ", meta_data)```

### Expected results

Loading the Trace dataset 

### Actual results

```Error: urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```

### Versions

<details>
System:
    python: 3.10.8 (v3.10.8:aaaf517424, Oct 11 2022, 10:14:40) [Clang 13.0.0 (clang-1300.0.29.30)]
executable: /usr/local/bin/python3.10
   machine: macOS-12.5-arm64-arm-64bit

Python dependencies:
          pip: 21.3.1
   setuptools: 67.6.0
 scikit-learn: 1.1.3
         aeon: 0.8.1
  statsmodels: None
        numpy: 1.23.5
        scipy: 1.9.3
       pandas: 2.0.3
   matplotlib: 3.7.1
       joblib: 1.2.0
        numba: 0.56.4
     pmdarima: None
      tsfresh: None
<details>

**Comment by CodeLionX** [comment]
Possible duplicate of #1502. Can you verify, whether this issue persists with the current development version of aeon (`main` branch)?

**Comment by simiaolin** [comment]
> Possible duplicate of #1502. Can you verify, whether this issue persists with the current development version of aeon (`main` branch)?

#1502 was closed last week. The error messages are different. The aeon version I am using is aeon: 0.8.1.

**Comment by CodeLionX** [comment]
I cannot reproduce this bug with a recent version of aeon. Please update to `aeon>=0.9.0`.

IMHO, we can close this and #1502.

<details>

---

Test on the current `main`-branch and with the new version of aeon 0.9.0 (published yesterday):

```python
from aeon import show_versions
from aeon.datasets import load_classification


X, y, meta_data = load_classification("Trace", return_metadata=True)
print(f"Shape of X = {X.shape}")
print(f"Metadata = {meta_data}")

show_versions()
```
Produces:
```
Shape of X = (200, 1, 275)
Metadata = {'problemname': 'trace', 'timestamps': False, 'missing': False, 'univariate': True, 'equallength': True, 'classlabel': True, 'targetlabel': False, 'class_values': ['1', '2', '3', '4']}

System:
    python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
executable: /home/sebastian/.conda/envs/aeon/bin/python
   machine: Linux-5.15.0-107-generic-x86_64-with-glibc2.35

Python dependencies:
          pip: 23.3.1
   setuptools: 68.2.2
 scikit-learn: 1.4.1.post1
         aeon: 0.8.1
  statsmodels: None
        numpy: 1.23.5
        scipy: 1.10.0
       pandas: 2.0.3
   matplotlib: 3.8.3
       joblib: 1.3.2
        numba: 0.56.4
     pmdarima: None
      tsfresh: None
```

</details>
