### ISSUE TITLE
[MNT] Add `pre-commit` hook for `mypy`

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [aeon-toolkit/aeon#1856]
### Describe the issue

From July 26 2024 meeting. 

There are a few type hint errors, and no method to easily discover these. We should include some automated type checking for type hints in `pre-commit`. 

### Suggest a potential alternative/fix

The first package that comes to mind for this is `mypy`, but it does not necessarily have to be this.

i.e.

```
- repo: https://github.com/pre-commit/mirrors-mypy
   rev: v1.0.1
   hooks:
     - id: mypy
       files: aeon/
       additional_dependencies: [ pytest ]
```

This should be set up to only be run manually for now, however. There are a lot of breakages that we do not want to do at once.
